version: "3.7"

services:
  minio:
    container_name: minio
    image: "minio/minio:latest"
    networks:
      - scraping
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER_NAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${BUCKET_NAME}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always

  db:
    container_name: db
    image: "postgres:latest"
    networks:
      - scraping
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: always

  scraping:
    container_name: scraping
    build: scraper/.
    networks:
      - scraping
    depends_on:
      - db
      - minio
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_TABLE=${POSTGRES_TABLE}

      - MINIO_USER_NAME=${MINIO_USER_NAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - BUCKET_NAME=${BUCKET_NAME}

volumes:
  minio_data:
  database_data:


networks:
  scraping:
    driver: bridge
