version: "3.7"

services:
  minio:
    container_name: minio
    image: "minio/minio:latest"
    networks:
      - scraping
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${ACCESS_KEY}
      - MINIO_SECRET_KEY=${SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${BUCKET_NAME}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always

volumes:
  minio_data:


networks:
  scraping:
    driver: bridge
