version: "3.7"

services:
  minio:
    container_name: minio
    image: "minio/minio:latest"
    networks:
      - scraping
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_DEFAULT_BUCKETS=files
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  minio_data:


networks:
  scraping:
    driver: bridge
